# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hannu Hartikainen
tagline:          'Twin father, occasional hacker'
description:      'I write here when I have time. See, I never have time. ;)'
url:              http://blog.hannuhartikainen.fi/

author:
  name:           'Hannu Hartikainen'
  url:            https://github.com/dancek

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dancek/lanyon
